package mm.simple.model.helper;

public class Const {
public static String[][] languages = 
new String[][]{ {"Afghanistan","Afgánistán","Afganistan"},
				{"Albania","Albánie","Albánsko"},
				{"Algeria","Alžírsko","Alžírsko"},
				{"Argentina","Argentina","Argentína"},
				{"Armenia","Arménie","Arménsko"},
				{"Aruba","Aruba","Aruba"},
				{"Australia","Austrálie","Austrália"},
				{"Belgium","Belgie","Belgicko"},
				{"Belarus","Belorusko","Bielorusko"},
				{"Bhutan","Bhután","Bhután"},
				{"Bosnia and Herzegowina","Bosna a Hercegovina","Bosna a Hercegovina"},
				{"Brazil","Brazílie","Brazília"},
				{"Bulgaria","Bulharsko","Bulharsko"},
				{"Burkina Faso","Burkina Faso","Burkina Faso"},
				{"Czech Republic","Cesko","Cesko"},
				{"China","Cína","Cína"},
				{"Denmark","Dánsko","Dánsko"},
				{"Egypt","Egypt","Egypt"},
				{"Ecuador","Ekvádor","Ekvádor"},
				{"Estonia","Estonsko","Estónsko"},
				{"Philippines","Filipíny","Filipíny"},
				{"Finland","Finsko","Fínsko"},
				{"France","Francie","Francúzsko"},
				{"Georgia","Gruzie","Gruzínsko"},
				{"Hong Kong","Hong Kong","Hong Kong"},
				{"Chile","Chile","Chile"},
				{"Croatia","Chorvatsko","Chorvatsko"},
				{"India","Indie","India"},
				{"Indonesia","Indonésie","Indonézia"},
				{"Iraq","Irák","Irak"},
				{"Iran","Írán","Írán"},
				{"Ireland","Irsko","Írsko"},
				{"Iceland","Island","Island"},
				{"Italy","Itálie","Taliansko"},
				{"Israel","Izrael","Izrael"},
				{"Jamaica","Jamajka","Jamajka"},
				{"Japan","Japonsko","Japonsko"},
				{"South Africa" ,"Jižní Afrika", "Južná Afrika"},
				{"South Korea","Jižní Korea","Južná Kórea"},
				{"Jordan","Jordánsko","Jordánsko"},
				{"Cambodia","Kambodža","Kambodža"},
				{"Cameroon","Kamerun","Kamerun"},
				{"Canada","Kanada","Kanada"},
				{"Kazachstan","Kazachstán","Kazachstan"},
				{"Kenya","Kena","Kena"},
				{"Colombia","Kolumbie","Kolumbia"},
				{"Cuba","Kuba","Kuba"},
				{"Lebanon","Libanon","Libanon"},
				{"Lithuania","Litva","Litva"},
				{"Latvia","Lotyšsko","Lotyšsko"},
				{"Luxembourg","Lucembursko","Luxembursko"},
				{"Hungary","Madarsko","Madarsko"},
				{"Macedonia","Makedonie","Macedónsko"},
				{"malaysia","Malajsie","Malajzia"},
				{"Malawi","Malawi","Malawi"},
				{"Malta","Malta","Malta"},
				{"Morocco","Maroko","Maroko"},
				{"Mexico","Mexiko","Mexiko"},
				{"Monaco","Monako","Monako"},
				{"Mongolia","Mongolsko","Mongolsko"},
				{"Germany","Nemecko","Nemecko"},
				{"Niger","Niger","Niger"},
				{"Netherlands","Nizozemsko","Holandsko"},
				{"Norway","Norsko","Nórsko"},
				{"New Zealand","Nový Zéland","Nový Zéland"},
				{"Pakistan","Pákistán","Pakistan"},
				{"Palestine","Palestina","Palestína"},
				{"Peru","Peru","Peru"},
				{"Poland","Polsko","Polsko"},
				{"Puerto Rico","Portoriko","Portoriko"},
				{"Portugal","Portugalsko","Portugalsko"},
				{"Austria","Rakousko","Rakúsko"},
				{"Romania","Rumunsko","Rumunsko"},
				{"Russia","Rusko","Rusko"},
				{"Greece","Recko","Grécko"},
				{"Senegal","Senegal","Senegal"},
				{"Korea","Korea","Korea"},
				{"Singapore","Singapur","Singapur"},
				{"Slovakia","Slovensko","Slovensko"},
				{"Slovenia","Slovinsko","Slovinsko"},
				{"Spain","Španelsko","Španielsko"},
				{"United Arab Emirates","Spojené arabské emiráty","Spojené arabské emiráty"},
				{"Serbia","Srbsko","Srbsko"},
				{"Sweden","Švédsko","Švédsko"},
				{"Switzerland","Švýcarsko","Švajciarsko"},
				{"Taiwan","Taiwan","Taiwan"},
				{"Thailand","Thajsko","Thajsko"},
				{"Tunisia","Tunisko","Tunisko"},
				{"Turkey","Turecko","Turecko"},
				{"Ukraine","Ukrajina","Ukrajina"},
				{"Uruguay","Uruguay","Uruguaj"},
				{"USA", "USA", "USA" },
				{"Great britain","Velká Británie","Velká Británia"},
				{"Vietnam","Vietnam","Vietnam"},
				{"Tanzania","Tanzania","Tanzania"},
				{"United","Kingdom","Anglie","Anglicko"},
				{"Czech Republic","Cesko","Cesko"},
				{"Costa Rica","Kostarika","Kostarika"},
				{"Korea","Korea","Korea"},
				{"Serbia and Montenegro","Srbsko a Cierna Hora","Srbsko a Cierna Hora"},
				{"Namibia","Namíbia","Namíbia"},
				{"Bolivia","Bolivia","Bolivia"},
				{"Botswana","Botswana","Botswana"},
				{"Cyprus","Cyprus","Cyprus"},
				{"Paraguay","Paraguaj","Paraguaj"},
				{"Yugoslavia","Juhoslávia","Juhoslávia"} };

public static String[][] genres = new String[][]{
		{"Action","Akcní","Akcný"},
		{"Crime","Krimi","Krimi"},
		{"Comedy","Komedie","Komédia"},
		{"Biography","Životopisný","Životopisný"},
		{"Drama","Drama","Dráma"},
		{"Horror","Horor","Horor"},
		{"Adventure","Dobrodružný","Dobrodružný"},
		{"Family","Rodinný","Rodinný"},
		{"Thriller","Thriller","Thriller"},
		{"Animation","Animovaný","Animovaný"},
		{"Mystery","Mysteriózní","Mysteriózny"},
		{"Science Fiction","Sci-Fi","Sci-Fi"},
		{"Fantasy","Fantasy","Fantasy"},
		{"History","Historický","Historický"},
		{"Documentary","Dokumentární","Dokumentárny"},
		{"Western","Western","Western"},
		{"Romance","Romantický","Romantický"},
		{"Music","Hudební","Hudobný"},
		{"War" ,"Válecný","Vojnový"},
		{"Sport","Sportovní","Športový"},
		{"Musical","Muzikál","Muzikál"}
		};
}

